### PR TITLE
mesa: disable futexes mistakenly enabled by having linux/futex.h

### PR DESCRIPTION
**Pull request by no92**

### CODE REVIEW

**Review by Dennisbonke — CHANGES_REQUESTED** [review]
LGTM but please bump the revision of `mesa` too.

**Comment by ArsenArsen** [comment]
I think we should start documenting what patches fix too.  Could you add a bit of commentary below the `---` line?

**Comment by no92** [comment]
Addressed the comments raised above.

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Pull request merged**
