### PR TITLE
qemu: bump to 8.1.4 and add dmalog support

### PR DESCRIPTION
**Pull request by no92**
This PR depends on managarm/xbstrap#74.

### CODE REVIEW

**Review by ElectrodeYT — APPROVED** [review]
LGTM ASAP, when the containerless tools PR has been merged

**Comment by no92** [comment]
Updated to use qemu 8.1.1

**Comment by Dennisbonke** [comment]
Blocking on new release

**Comment by no92** [comment]
Updated to qemu 8.1.4

**Comment by qookei** [comment]
We can drop `0002-qemu-thread-posix-patch-out-pthread_attr_setdetachst.patch`, `pthread_attr_setdetachstate` is now supported in mlibc.

**Comment by qookei** [comment]
Pretty sure the `host_lseek` part of patch 4 can also be dropped since we switched to the Linux ABI?

**Review by qookei — APPROVED** [review]

**Pull request merged**
