### PR TITLE
xbbs fixes

### PR DESCRIPTION
**Pull request by no92**

### CODE REVIEW

**Review by Dennisbonke — CHANGES_REQUESTED** [review]
NAK. This solution for graphene breaks downstream users that use gobject-introspection (Aka the GNOME stack).

**Comment by no92** [comment]
Dropped the `graphene` commit as discussed on Discord.

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Pull request merged**
