### PR TITLE
llvm: Update from version 14.0.5 to 16.0.6

### PR DESCRIPTION
**Pull request by Dennisbonke**
Also includes a bump for `mesa`. This LLVM version is needed for the `.clang-format` file I'm about to PR in.

### CODE REVIEW

**Review by no92 — APPROVED** [review]
LGTM

**Comment by Dennisbonke** [comment]
Hold this because I need to rebuild rust too as a sanity check.

**Comment by Dennisbonke** [comment]
Blocked on rust not compiling with llvm 16.0.1.

**Comment by Dennisbonke** [comment]
This is good to go after CI is approving.

**Review by no92 — APPROVED** [review]
LGTM

**Review by ElectrodeYT — APPROVED** [review]
LGTM

**Pull request merged**
