### PR TITLE
rust: update rustc to 1.58.1

### PR DESCRIPTION
**Pull request by 64**
Threads are still broken as per https://github.com/managarm/mlibc/issues/389.

### CODE REVIEW

**Comment by avdgrinten** [comment]
Are threads also broken in 1.57?

**Review by Dennisbonke — CHANGES_REQUESTED** [review]
Looks good to me but we can merge some patches back into one I think. Personally, I'd merge `rust-libc` patch 3 and 4 into 1, and `rust` patch 3 into patch 1.

**Comment by Dennisbonke** [comment]
> Are threads also broken in 1.57?

Seems like they are.

**Comment by 64** [comment]
> Are threads also broken in 1.57?

Yes, it's purely a mlibc issue as far as we can tell

**Comment by avdgrinten** [comment]
Alright, then that doesn't block merging.

**Comment by 64** [comment]
Confirmed that with managarm/mlibc#392 applied, threads work again:

image

**Pull request merged**
