### PR TITLE
gcc: Update from version 10.3.0 to 11.1.0

### PR DESCRIPTION
**Pull request by Dennisbonke**
This PR updates `gcc` and the toolchain to version 11.1.0.

This PR is blocked on managarm/managarm#369 and managarm/frigg#10

### CODE REVIEW

**Comment by avdgrinten** [comment]
Was the patch rebased or recreated?

**Comment by Dennisbonke** [comment]
An attempt at rebasing was made, when that failed I tried to apply the old patch with `git am --3way` and modified it as needed. It does seem that one line got erroneously dropped from the patch, so I'll add that one back.

**Comment by Dennisbonke** [comment]
Issue with the patch has been fixed, and this PR can be merged whenever github actions is done and approves of it.

**Comment by Dennisbonke** [comment]
@qookei has indicated on Discord that the patch itself looks good, so with that approval I'm going to merge this PR.

**Pull request merged**
