### PR TITLE
Various new ports

### PR DESCRIPTION
**Pull request by Dennisbonke**
This PR adds the following ports:

- `libtasn1`, required dependency for `p11-kit` and used to manage ASN.1 data structures,
- `p11-kit`, an interface for Public-Key Cryptography Standard 11, also used in generating the ca-certificate store,
- `xprop`, a property displayer for X,
- `xset`, a tool for setting miscellaneous X server parameters.

Furthermore, the version number for `libuv` was fixed and the list of dependencies in the readme and Dockerfile have been updated.

This PR is blocked on managarm/mlibc#187

### CODE REVIEW

**Comment by avdgrinten** [comment]
Why do we need additional packages on the host?

Are some of the patches taken from other OSes? Do they need attribution?

**Comment by Dennisbonke** [comment]
`p11-kit` generates some header files at build time using programs from `libtasn1-bin`, however due to those files going in the pkg-build dir and p11-kit looking from the source dir this fails, which is why I included the copy generated on my host as a patch. Regarding patches, the distribution specific hook was taken from Beyond Linux From Scratch, the other 2 are local work

**Comment by avdgrinten** [comment]
What's the license of BLFS?

**Comment by Dennisbonke** [comment]
The licenses of BLFS are Creative Commons Attribution-NonCommercial-ShareAlike 2.0 and the MIT license. I’m guessing the patch would fall under the MIT license here

**Comment by avdgrinten** [comment]
But in that case the patch needs attribution. State the origin, copyright holder and license in the patches commit message.

**Comment by Dennisbonke** [comment]
Yeah I just realized that. Good catch, I’ll modify that later today

**Comment by avdgrinten** [comment]
Alright, LGTM.

**Pull request merged**
