### PR TITLE
Add checksums to url type sources

### PR DESCRIPTION
**Pull request by no92**
Blocked on managarm/xbstrap#63

### CODE REVIEW

**Review by Dennisbonke — APPROVED** [review]
LGTM, actual usability is pending some xbstrap PRs and a release but I've been assured it can be merged without breaking xbbs.

**Comment by Dennisbonke** [comment]
Or not as the PR itself says, whoops. Holding pending managarm/xbstrap#63 and a release containing it.

**Comment by ArsenArsen** [comment]
isn't xbstrap forward compatible? iirc additional parameters are set to not fail validation

**Comment by no92** [comment]
Rebased on master and updated for new naming of `mandate_hashes`.

**Comment by avdgrinten** [comment]
LGTM but blocked on a new xbstrap release.

**Comment by no92** [comment]
Rebased onto current master.

**Review by 64 — APPROVED** [review]

**Review by 64 — APPROVED** [review]

**Comment by ArsenArsen** [comment]
Is this still up-to-date?

**Comment by no92** [comment]
Yep, I verified that the hashes are correct for current master.

**Review by ArsenArsen — APPROVED** [review]

**Pull request merged**
